---
- hosts: all
  remote_user: vagrant
  vars:
  - ansible_python_interpreter: /usr/bin/python2.7
  tasks:
  - name: yum install epel repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
         state=present
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install ius repo
    yum: name=https://centos7.iuscommunity.org/ius-release.rpm
         state=present
    become: yes
    become_user: root
    become_method: sudo
  - name: yum update
    yum: name=*
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install python
    yum: name=python
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install python-pip
    yum: name=python-pip
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install python-virtualenv
    yum: name=python-virtualenv
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install python-setuptools
    yum: name=python-setuptools
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install rpm-build
    yum: name=rpm-build
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install redhat-rpm-config
    yum: name=redhat-rpm-config
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install yum-utils
    yum: name=yum-utils
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install Development Tools
    yum: name="@Development tools"
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install python35u
    yum: name=python35u
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: yum install python35u-pip
    yum: name=python35u-pip
         state=latest
    become: yes
    become_user: root
    become_method: sudo
  - name: pip install beautifulsoup4
    pip: name=beautifulsoup4
         state=latest
         executable=/usr/bin/pip3.5
         extra_args=--user
  - name: pip install invoke
    pip: name=invoke
         state=latest
         executable=/usr/bin/pip3.5
         extra_args=--user
  - name: pip install requests
    pip: name=requests
         state=latest
         executable=/usr/bin/pip3.5
         extra_args=--user
  - name: pip install version_utils
    pip: name=version_utils
         state=latest
         executable=/usr/bin/pip3.5
         extra_args=--user
  - name: copy invoke/tasks.py
    copy: src=./invoke/tasks.py
          dest=/home/vagrant/tasks.py
          owner=vagrant
          group=vagrant
          mode="u=rw,g=r,o=r"


  # - name: install vim-lite
  #   pkgng: name=vim-lite state=present
  #   become: yes
  #   become_user: root
  #   become_method: sudo
  # - name: install git
  #   pkgng: name=git state=present
  #   become: yes
  #   become_user: root
  #   become_method: sudo
  # - name: clone crochet
  #   git: repo=https://github.com/freebsd/crochet
  #        dest=/home/vagrant/crochet
  #        version=master
  # - name: copy config.rpi2.sh
  #   copy: src=./config.rpi2.sh
  #         dest=/home/vagrant/crochet/config.rpi2.sh
  #         owner=vagrant
  #         group=vagrant
  #         mode="u=rw,g=r,o=r"
  # - name: copy config.cuboxi.sh
  #   copy: src=./config.cuboxi.sh
  #         dest=/home/vagrant/crochet/config.cuboxi.sh
  #         owner=vagrant
  #         group=vagrant
  #         mode="u=rw,g=r,o=r"
  # - name: workaround ansible bug - delete empty file created by ansible 'copy'
  #   raw: rm "/home/vagrant/0:"
  # - name: install u-boot-rpi2
  #   pkgng: name=sysutils/u-boot-rpi2 state=present
  #   become: yes
  #   become_user: root
  #   become_method: sudo
  # - name: clone svn repo in /home/vagrant/crochet/src
  #   subversion: repo=svn://svn.freebsd.org/base/head
  #               dest=/home/vagrant/crochet/src
  #               executable=/usr/bin/svnlite
  #               revision=HEAD
  #               switch=no
  #               force=yes
